<a href="https://colab.research.google.com/github/manoj-mathivanan/cnn-demo/blob/main/Exercises/E0%20Pytorch/pytorch_fundamentals_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch Fundamentals Exercise**



In [1]:
# Import all the necessary libraries here
import torch

### **Q1 Create a random tensor with shape `(7, 7)`**


In [4]:
# Your code here
matrix1 = torch.rand(7, 7)
print(matrix1)

tensor([[0.8797, 0.6570, 0.8940, 0.9844, 0.4731, 0.6474, 0.9112],
        [0.5101, 0.7798, 0.8910, 0.9802, 0.1784, 0.0479, 0.8882],
        [0.4132, 0.1458, 0.4947, 0.3170, 0.7848, 0.4417, 0.4174],
        [0.5553, 0.8278, 0.0013, 0.8217, 0.2072, 0.4652, 0.0982],
        [0.6137, 0.8912, 0.1103, 0.9731, 0.5374, 0.2465, 0.2354],
        [0.1467, 0.8325, 0.2956, 0.7920, 0.9327, 0.2418, 0.4154],
        [0.3952, 0.3465, 0.4470, 0.6049, 0.2348, 0.3347, 0.0119]])


### **Q2 Perform a matrix multiplication on the tensor from Q1 with another random tensor with shape `(1, 7)`**

In [5]:
# Your code here
matrix2 = torch.rand(1, 7)
output1 = torch.matmul(matrix1, matrix2.T)
print(output1)

tensor([[1.5739],
        [1.3063],
        [0.8193],
        [0.5902],
        [0.7892],
        [0.8613],
        [0.3898]])


### **Q3 Set the random seed to `0` and do Q1 & Q2 over again**

In [26]:
# Your code here
torch.manual_seed(0)
matrix1 = torch.rand(7, 7)
matrix2 = torch.rand(7, 1)
print(matrix1)
print(torch.matmul(matrix1, matrix2))

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### **Q4 Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent?**
  * If there is, set the GPU random seed to `1234`

In [14]:
# Your code here
torch.cuda.manual_seed(1234)


### **Q5 Create two random tensors of shape `(2, 3)` and send them both to the GPU. Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed)**

In [19]:
# Your code here
torch.manual_seed(1234)
matrix1 = torch.rand(2, 3)
matrix2 = torch.rand(2, 3)


### **Q6 Perform a matrix multiplication on the tensors you created in Q5**

In [20]:
# Your code here
output1 = torch.matmul(matrix1, matrix2.T)
print(output1)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])


### **Q7 Find the maximum and minimum values of the output of Q6**

In [22]:
# Your code here
print(output1.max())
print(output1.min())

tensor(0.5617)
tensor(0.3647)


### **Q8 Find the maximum and minimum index values of the output of Q6**

In [23]:
# Your code here
print(output1.argmax())
print(output1.argmin())

tensor(3)
tensor(0)


### **Q9 Perform a matrix multiplication on the tensors you created in Q5 in `numpy` and convert the output to tensor**

In [33]:
# Your code here
matrixnumpy1 = matrix1.numpy()
matrixnumpy2 = matrix2.numpy()
matrixoutput1 = matrixnumpy1.dot(matrixnumpy2.T)
print(matrixoutput1)
output2 = torch.from_numpy(matrixoutput1)
print(output2)

ValueError: shapes (7,7) and (1,7) not aligned: 7 (dim 1) != 1 (dim 0)


### **Q10 Make a random tensor with shape `(1, 1, 1, 10)` and then convert it to a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape**

In [32]:
# Your code here
torch.manual_seed(7)
shape1 = torch.rand(1,1,1,10)
print(shape1)
print(shape1.shape)
squeezedShape = torch.squeeze(shape1)
print(squeezedShape)
print(squeezedShape.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
