<a href="https://colab.research.google.com/github/manoj-mathivanan/cnn-demo/blob/main/Exercises/E0%20Pytorch/pytorch_fundamentals_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch Fundamentals Exercise**



In [1]:
# Import all the necessary libraries here
import torch

### **Q1 Create a random tensor with shape `(7, 7)`**


In [2]:
# Your code here
matrix1 = torch.rand(7, 7)
print(matrix1)

tensor([[0.5770, 0.7538, 0.9968, 0.8315, 0.8176, 0.0144, 0.2545],
        [0.7091, 0.1000, 0.9488, 0.5833, 0.7116, 0.7448, 0.0455],
        [0.6610, 0.3300, 0.1165, 0.9744, 0.6958, 0.6145, 0.9827],
        [0.1720, 0.0606, 0.8284, 0.7201, 0.1861, 0.2968, 0.8923],
        [0.6558, 0.2967, 0.2928, 0.5109, 0.5396, 0.1899, 0.7965],
        [0.1986, 0.6725, 0.7818, 0.5431, 0.6891, 0.5571, 0.9136],
        [0.8100, 0.3730, 0.4879, 0.3501, 0.9202, 0.6442, 0.0588]])


### **Q2 Perform a matrix multiplication on the tensor from Q1 with another random tensor with shape `(1, 7)`**

In [3]:
# Your code here
matrix2 = torch.rand(1, 7)
output1 = torch.matmul(matrix1, matrix2.T)
print(output1)

tensor([[2.9282],
        [2.8199],
        [3.0388],
        [2.4217],
        [2.3862],
        [2.8245],
        [2.4712]])


### **Q3 Set the random seed to `0` and do Q1 & Q2 over again**

In [4]:
# Your code here
torch.manual_seed(0)
matrix1 = torch.rand(7, 7)
matrix11 = torch.rand(7, 7)
print(matrix1)
print(matrix11)

matrix2 = torch.rand(7, 1)
print(torch.matmul(matrix1, matrix2))

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056],
        [0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038],
        [0.6511, 0.7745, 0.4369, 0.5191, 0.6159, 0.8102, 0.9801],
        [0.1147, 0.3168, 0.6965, 0.9143, 0.9351, 0.9412, 0.5995],
        [0.0652, 0.5460, 0.1872, 0.0340, 0.9442, 0.8802, 0.0012],
        [0.5936, 0.4158, 0.4177, 0.2711, 0.6923, 0.2038, 0.6833],
        [0.7529, 0.8579, 0.6870, 0.0051, 0.1757, 0.7497, 0.6047]])
tensor([[0.7494],
        [1.2264],
        [1.6560],
        [1.8974],
  

### **Q4 Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent?**
  * If there is, set the GPU random seed to `1234`

In [5]:
# Your code here
torch.cuda.manual_seed(1234)


### **Q5 Create two random tensors of shape `(2, 3)` and send them both to the GPU. Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed)**

In [6]:
# Your code here
torch.manual_seed(1234)
matrix1 = torch.rand(2, 3)
matrix2 = torch.rand(2, 3)

print(matrix1)
print(matrix2)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Device: {device}')

matrix1_on_gpu = matrix1.to(device)
matrix2_on_gpu = matrix2.to(device)

print(matrix1_on_gpu)
print(matrix2_on_gpu)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])
Device: cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])



### **Q6 Perform a matrix multiplication on the tensors you created in Q5**

In [7]:
# Your code here
output1 = torch.matmul(matrix1, matrix2.T)
print(output1)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])


### **Q7 Find the maximum and minimum values of the output of Q6**

In [8]:
# Your code here
print(output1.max())
print(output1.min())

tensor(0.5617)
tensor(0.3647)


### **Q8 Find the maximum and minimum index values of the output of Q6**

In [9]:
# Your code here
print(output1.argmax())
print(output1.argmin())

tensor(3)
tensor(0)


### **Q9 Perform a matrix multiplication on the tensors you created in Q5 in `numpy` and convert the output to tensor**

In [10]:
# Your code here
matrixnumpy1 = matrix1.numpy()
matrixnumpy2 = matrix2.numpy()
matrixoutput1 = matrixnumpy1.dot(matrixnumpy2.T)
print(matrixoutput1)
output2 = torch.from_numpy(matrixoutput1)
print(output2)

[[0.36473012 0.47088534]
 [0.51838267 0.5617257 ]]
tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])



### **Q10 Make a random tensor with shape `(1, 1, 1, 10)` and then convert it to a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape**

In [18]:
# Your code here
torch.manual_seed(7)
shape1 = torch.rand(1,1,1,10)
print(shape1)
print(shape1.shape)
squeezedShape = torch.squeeze(shape1)
print(squeezedShape)
print(squeezedShape.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
